# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/example_top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_emc_0_0 || ORIG_REF_NAME==system_axi_emc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_0/bd_44e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_emc_0_0 || ORIG_REF_NAME==system_axi_emc_0_0} -quiet] -quiet

# XDC: bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_emc_0_0 || ORIG_REF_NAME==system_axi_emc_0_0} -quiet] -quiet

# XDC: bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m01s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m01arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m01rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m01awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m01wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m01bn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00bn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_0/ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/system_ooc.xdc

# XDC: E:/CE/FPGA/PD/Code/My/WaveWidth1-Comments/PLToPS1.srcs/MonopulseEx_Arithmetic/new/MonopulseEx_Arithmetic_ooc.xdc

# XDC: E:/CE/FPGA/PD/Code/My/WaveWidth1-Comments/PLToPS1.srcs/AD9481/new/AD9481_ooc.xdc

# XDC: E:/CE/FPGA/PD/Code/My/WaveWidth1-Comments/PLToPS1.srcs/Phase/new/Phase_ooc.xdc
