set_property SRC_FILE_INFO {cfile:e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc rfile:../../../PLToPS1.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:system_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/constrs_1/imports/imports/example_top.xdc rfile:../../../PLToPS1.srcs/constrs_1/imports/imports/example_top.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:3 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:4 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:5 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:6 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_ar_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:7 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_aw_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:8 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_w_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:9 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:10 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:11 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:12 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:13 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:14 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:15 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:16 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:17 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_b_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:18 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_r_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:19 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:20 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:21 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:22 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:23 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:24 order:LATE scoped_inst:{system_i/axi_smc/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:25 order:LATE scoped_inst:{system_i/axi_smc/inst/m01_nodes/m01_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:26 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:27 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:28 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:29 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:30 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:31 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:D:/Software/Xilinx17.4/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:32 order:LATE scoped_inst:{system_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A20" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A18" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B21" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F18" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H17" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F19" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J19" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F20" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G22" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F22" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H19" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G19" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G20" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G17" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G21" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W21" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V21" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V22" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V23" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y22" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H22" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W24" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P25" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L24" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H24" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W25" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R25" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L25" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G25" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L23" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K26" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J23" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J24" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H23" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H26" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G26" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W23" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y26" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J25" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y25" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W26" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U25" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U24" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U26" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V24" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R23" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T23" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T25" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T24" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F25" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P23" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N26" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P24" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R26" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N23" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M24" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N24" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M25" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K23" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M26" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J26" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V26" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P26" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K25" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G24" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y21" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U21" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R21" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P21" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y23" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R22" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T22" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U22" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U20" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T20" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J21" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L20" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N22" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M20" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L22" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N21" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K20" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R20" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J20" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P20" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H21" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M22" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K22" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C23" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A22" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B24" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C8 [get_ports clk100m_i]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10 [get_ports init_calib_complete]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports rst_key]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports tg_compare_error]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC14 [get_ports pld_clk_p]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC13 [get_ports dco_p]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB17 [get_ports pen]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB16 [get_ports pll_ce]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC17 [get_ports pll_rst_n]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD15 [get_ports adc_pd]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD16 [get_ports {adc_p1[7]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC16 [get_ports {adc_p1[6]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {adc_p1[5]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {adc_p1[4]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {adc_p1[3]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA17 [get_ports {adc_p1[2]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {adc_p1[1]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y15 [get_ports {adc_p1[0]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports {adc_p2[7]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC11 [get_ports {adc_p2[6]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE17 [get_ports {adc_p2[5]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF17 [get_ports {adc_p2[4]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {adc_p2[3]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE16 [get_ports {adc_p2[2]}]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {adc_p2[1]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {adc_p2[0]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {dac_p1[9]}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {dac_p1[8]}]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12 [get_ports {dac_p1[7]}]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {dac_p1[6]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE11 [get_ports {dac_p1[5]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF10 [get_ports {dac_p1[4]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE10 [get_ports {dac_p1[3]}]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD11 [get_ports {dac_p1[2]}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC12 [get_ports {dac_p1[1]}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10 [get_ports {dac_p1[0]}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports {dac_p2[9]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports {dac_p2[8]}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {dac_p2[7]}]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {dac_p2[6]}]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {dac_p2[5]}]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports {dac_p2[4]}]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10 [get_ports {dac_p2[3]}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports {dac_p2[2]}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11 [get_ports {dac_p2[1]}]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports {dac_p2[0]}]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF14 [get_ports dac_pll_locked]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF15 [get_ports dac_rst]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports SendIRQ]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {GPIO_0_tri_o[0]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {GPIO2_0_tri_o[0]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_CLK]]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list u_ila_1_clk_out2]]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_CLK]]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list u_ila_1_clk_out2]]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {example_top/app_addr_begin[0]} {example_top/app_addr_begin[1]} {example_top/app_addr_begin[2]} {example_top/app_addr_begin[3]} {example_top/app_addr_begin[4]} {example_top/app_addr_begin[5]} {example_top/app_addr_begin[6]} {example_top/app_addr_begin[7]} {example_top/app_addr_begin[8]} {example_top/app_addr_begin[9]} {example_top/app_addr_begin[10]} {example_top/app_addr_begin[11]} {example_top/app_addr_begin[12]} {example_top/app_addr_begin[13]} {example_top/app_addr_begin[14]} {example_top/app_addr_begin[15]} {example_top/app_addr_begin[16]} {example_top/app_addr_begin[17]} {example_top/app_addr_begin[18]} {example_top/app_addr_begin[19]} {example_top/app_addr_begin[20]} {example_top/app_addr_begin[21]} {example_top/app_addr_begin[22]} {example_top/app_addr_begin[23]} {example_top/app_addr_begin[24]} {example_top/app_addr_begin[25]} {example_top/app_addr_begin[26]} {example_top/app_addr_begin[27]} {example_top/app_addr_begin[28]}]]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {example_top/Period_count[0]} {example_top/Period_count[1]} {example_top/Period_count[2]} {example_top/Period_count[3]} {example_top/Period_count[4]} {example_top/Period_count[5]}]]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {example_top/app_wdf_data[0]} {example_top/app_wdf_data[1]} {example_top/app_wdf_data[2]} {example_top/app_wdf_data[3]} {example_top/app_wdf_data[4]} {example_top/app_wdf_data[5]} {example_top/app_wdf_data[6]} {example_top/app_wdf_data[7]} {example_top/app_wdf_data[8]} {example_top/app_wdf_data[9]} {example_top/app_wdf_data[10]} {example_top/app_wdf_data[11]} {example_top/app_wdf_data[12]} {example_top/app_wdf_data[13]} {example_top/app_wdf_data[14]} {example_top/app_wdf_data[15]} {example_top/app_wdf_data[16]} {example_top/app_wdf_data[17]} {example_top/app_wdf_data[18]} {example_top/app_wdf_data[19]} {example_top/app_wdf_data[20]} {example_top/app_wdf_data[21]} {example_top/app_wdf_data[22]} {example_top/app_wdf_data[23]} {example_top/app_wdf_data[24]} {example_top/app_wdf_data[25]} {example_top/app_wdf_data[26]} {example_top/app_wdf_data[27]} {example_top/app_wdf_data[28]} {example_top/app_wdf_data[29]} {example_top/app_wdf_data[30]} {example_top/app_wdf_data[31]} {example_top/app_wdf_data[32]} {example_top/app_wdf_data[33]} {example_top/app_wdf_data[34]} {example_top/app_wdf_data[35]} {example_top/app_wdf_data[36]} {example_top/app_wdf_data[37]} {example_top/app_wdf_data[38]} {example_top/app_wdf_data[39]} {example_top/app_wdf_data[40]} {example_top/app_wdf_data[41]} {example_top/app_wdf_data[42]} {example_top/app_wdf_data[43]} {example_top/app_wdf_data[44]} {example_top/app_wdf_data[45]} {example_top/app_wdf_data[46]} {example_top/app_wdf_data[47]} {example_top/app_wdf_data[48]} {example_top/app_wdf_data[49]} {example_top/app_wdf_data[50]} {example_top/app_wdf_data[51]} {example_top/app_wdf_data[52]} {example_top/app_wdf_data[53]} {example_top/app_wdf_data[54]} {example_top/app_wdf_data[55]} {example_top/app_wdf_data[56]} {example_top/app_wdf_data[57]} {example_top/app_wdf_data[58]} {example_top/app_wdf_data[59]} {example_top/app_wdf_data[60]} {example_top/app_wdf_data[61]} {example_top/app_wdf_data[62]} {example_top/app_wdf_data[63]} {example_top/app_wdf_data[64]} {example_top/app_wdf_data[65]} {example_top/app_wdf_data[66]} {example_top/app_wdf_data[67]} {example_top/app_wdf_data[68]} {example_top/app_wdf_data[69]} {example_top/app_wdf_data[70]} {example_top/app_wdf_data[71]} {example_top/app_wdf_data[72]} {example_top/app_wdf_data[73]} {example_top/app_wdf_data[74]} {example_top/app_wdf_data[75]} {example_top/app_wdf_data[76]} {example_top/app_wdf_data[77]} {example_top/app_wdf_data[78]} {example_top/app_wdf_data[79]} {example_top/app_wdf_data[80]} {example_top/app_wdf_data[81]} {example_top/app_wdf_data[82]} {example_top/app_wdf_data[83]} {example_top/app_wdf_data[84]} {example_top/app_wdf_data[85]} {example_top/app_wdf_data[86]} {example_top/app_wdf_data[87]} {example_top/app_wdf_data[88]} {example_top/app_wdf_data[89]} {example_top/app_wdf_data[90]} {example_top/app_wdf_data[91]} {example_top/app_wdf_data[92]} {example_top/app_wdf_data[93]} {example_top/app_wdf_data[94]} {example_top/app_wdf_data[95]} {example_top/app_wdf_data[96]} {example_top/app_wdf_data[97]} {example_top/app_wdf_data[98]} {example_top/app_wdf_data[99]} {example_top/app_wdf_data[100]} {example_top/app_wdf_data[101]} {example_top/app_wdf_data[102]} {example_top/app_wdf_data[103]} {example_top/app_wdf_data[104]} {example_top/app_wdf_data[105]} {example_top/app_wdf_data[106]} {example_top/app_wdf_data[107]} {example_top/app_wdf_data[108]} {example_top/app_wdf_data[109]} {example_top/app_wdf_data[110]} {example_top/app_wdf_data[111]} {example_top/app_wdf_data[112]} {example_top/app_wdf_data[113]} {example_top/app_wdf_data[114]} {example_top/app_wdf_data[115]} {example_top/app_wdf_data[116]} {example_top/app_wdf_data[117]} {example_top/app_wdf_data[118]} {example_top/app_wdf_data[119]} {example_top/app_wdf_data[120]} {example_top/app_wdf_data[121]} {example_top/app_wdf_data[122]} {example_top/app_wdf_data[123]} {example_top/app_wdf_data[124]} {example_top/app_wdf_data[125]} {example_top/app_wdf_data[126]} {example_top/app_wdf_data[127]}]]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {example_top/state1[0]} {example_top/state1[1]} {example_top/state1[2]} {example_top/state1[3]}]]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list example_top/app_rd_data_valid]]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list example_top/ddr3read_en]]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list example_top/OnePeriod_flag]]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list example_top/Read_Fifo_full]]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list example_top/Read_Fifo_in_en1]]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list {example_top/Arithmetic_State[0]} {example_top/Arithmetic_State[1]} {example_top/Arithmetic_State[2]}]]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe8 [get_nets [list {example_top/Count[0]} {example_top/Count[1]} {example_top/Count[2]} {example_top/Count[3]} {example_top/Count[4]} {example_top/Count[5]} {example_top/Count[6]} {example_top/Count[7]} {example_top/Count[8]} {example_top/Count[9]} {example_top/Count[10]} {example_top/Count[11]} {example_top/Count[12]} {example_top/Count[13]} {example_top/Count[14]} {example_top/Count[15]}]]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe9 [get_nets [list {example_top/Read_Fifo_rusdw_o[0]} {example_top/Read_Fifo_rusdw_o[1]} {example_top/Read_Fifo_rusdw_o[2]} {example_top/Read_Fifo_rusdw_o[3]} {example_top/Read_Fifo_rusdw_o[4]} {example_top/Read_Fifo_rusdw_o[5]} {example_top/Read_Fifo_rusdw_o[6]} {example_top/Read_Fifo_rusdw_o[7]} {example_top/Read_Fifo_rusdw_o[8]} {example_top/Read_Fifo_rusdw_o[9]} {example_top/Read_Fifo_rusdw_o[10]}]]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe12 [get_nets [list {example_top/PeriodPoint_num[0]} {example_top/PeriodPoint_num[1]} {example_top/PeriodPoint_num[2]} {example_top/PeriodPoint_num[3]} {example_top/PeriodPoint_num[4]} {example_top/PeriodPoint_num[5]} {example_top/PeriodPoint_num[6]} {example_top/PeriodPoint_num[7]} {example_top/PeriodPoint_num[8]} {example_top/PeriodPoint_num[9]} {example_top/PeriodPoint_num[10]} {example_top/PeriodPoint_num[11]} {example_top/PeriodPoint_num[12]} {example_top/PeriodPoint_num[13]} {example_top/PeriodPoint_num[14]} {example_top/PeriodPoint_num[15]} {example_top/PeriodPoint_num[16]} {example_top/PeriodPoint_num[17]} {example_top/PeriodPoint_num[18]} {example_top/PeriodPoint_num[19]} {example_top/PeriodPoint_num[20]} {example_top/PeriodPoint_num[21]} {example_top/PeriodPoint_num[22]} {example_top/PeriodPoint_num[23]} {example_top/PeriodPoint_num[24]} {example_top/PeriodPoint_num[25]} {example_top/PeriodPoint_num[26]} {example_top/PeriodPoint_num[27]} {example_top/PeriodPoint_num[28]} {example_top/PeriodPoint_num[29]} {example_top/PeriodPoint_num[30]} {example_top/PeriodPoint_num[31]}]]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe14 [get_nets [list {example_top/Read_Fifo_Out_r[0]} {example_top/Read_Fifo_Out_r[1]} {example_top/Read_Fifo_Out_r[2]} {example_top/Read_Fifo_Out_r[3]} {example_top/Read_Fifo_Out_r[4]} {example_top/Read_Fifo_Out_r[5]} {example_top/Read_Fifo_Out_r[6]} {example_top/Read_Fifo_Out_r[7]} {example_top/Read_Fifo_Out_r[8]} {example_top/Read_Fifo_Out_r[9]} {example_top/Read_Fifo_Out_r[10]} {example_top/Read_Fifo_Out_r[11]} {example_top/Read_Fifo_Out_r[12]} {example_top/Read_Fifo_Out_r[13]} {example_top/Read_Fifo_Out_r[14]} {example_top/Read_Fifo_Out_r[15]}]]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe17 [get_nets [list {example_top/WaveState[0]} {example_top/WaveState[1]}]]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe19 [get_nets [list {example_top/Pulse_point_num[0]} {example_top/Pulse_point_num[1]} {example_top/Pulse_point_num[2]} {example_top/Pulse_point_num[3]} {example_top/Pulse_point_num[4]} {example_top/Pulse_point_num[5]} {example_top/Pulse_point_num[6]} {example_top/Pulse_point_num[7]} {example_top/Pulse_point_num[8]} {example_top/Pulse_point_num[9]} {example_top/Pulse_point_num[10]} {example_top/Pulse_point_num[11]} {example_top/Pulse_point_num[12]} {example_top/Pulse_point_num[13]} {example_top/Pulse_point_num[14]} {example_top/Pulse_point_num[15]}]]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe20 [get_nets [list {example_top/Monopulse_data1[0]} {example_top/Monopulse_data1[1]} {example_top/Monopulse_data1[2]} {example_top/Monopulse_data1[3]} {example_top/Monopulse_data1[4]} {example_top/Monopulse_data1[5]} {example_top/Monopulse_data1[6]} {example_top/Monopulse_data1[7]} {example_top/Monopulse_data1[8]} {example_top/Monopulse_data1[9]} {example_top/Monopulse_data1[10]} {example_top/Monopulse_data1[11]} {example_top/Monopulse_data1[12]} {example_top/Monopulse_data1[13]} {example_top/Monopulse_data1[14]} {example_top/Monopulse_data1[15]}]]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe21 [get_nets [list {example_top/Monopulse_data_1[0]} {example_top/Monopulse_data_1[1]} {example_top/Monopulse_data_1[2]} {example_top/Monopulse_data_1[3]} {example_top/Monopulse_data_1[4]} {example_top/Monopulse_data_1[5]} {example_top/Monopulse_data_1[6]} {example_top/Monopulse_data_1[7]}]]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe22 [get_nets [list {example_top/time_cnt[0]} {example_top/time_cnt[1]} {example_top/time_cnt[2]} {example_top/time_cnt[3]} {example_top/time_cnt[4]} {example_top/time_cnt[5]} {example_top/time_cnt[6]} {example_top/time_cnt[7]} {example_top/time_cnt[8]} {example_top/time_cnt[9]} {example_top/time_cnt[10]} {example_top/time_cnt[11]} {example_top/time_cnt[12]} {example_top/time_cnt[13]} {example_top/time_cnt[14]} {example_top/time_cnt[15]}]]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe23 [get_nets [list {example_top/ddr3read_en1[0]} {example_top/ddr3read_en1[1]} {example_top/ddr3read_en1[2]} {example_top/ddr3read_en1[3]} {example_top/ddr3read_en1[4]} {example_top/ddr3read_en1[5]} {example_top/ddr3read_en1[6]} {example_top/ddr3read_en1[7]} {example_top/ddr3read_en1[8]} {example_top/ddr3read_en1[9]} {example_top/ddr3read_en1[10]} {example_top/ddr3read_en1[11]} {example_top/ddr3read_en1[12]} {example_top/ddr3read_en1[13]} {example_top/ddr3read_en1[14]} {example_top/ddr3read_en1[15]} {example_top/ddr3read_en1[16]} {example_top/ddr3read_en1[17]} {example_top/ddr3read_en1[18]} {example_top/ddr3read_en1[19]} {example_top/ddr3read_en1[20]} {example_top/ddr3read_en1[21]} {example_top/ddr3read_en1[22]} {example_top/ddr3read_en1[23]} {example_top/ddr3read_en1[24]}]]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe24 [get_nets [list {example_top/ii[0]} {example_top/ii[1]} {example_top/ii[2]} {example_top/ii[3]} {example_top/ii[4]} {example_top/ii[5]} {example_top/ii[6]} {example_top/ii[7]} {example_top/ii[8]} {example_top/ii[9]} {example_top/ii[10]} {example_top/ii[11]} {example_top/ii[12]} {example_top/ii[13]} {example_top/ii[14]} {example_top/ii[15]}]]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe25 [get_nets [list {example_top/ddr3read_en2[0]} {example_top/ddr3read_en2[1]} {example_top/ddr3read_en2[2]} {example_top/ddr3read_en2[3]} {example_top/ddr3read_en2[4]} {example_top/ddr3read_en2[5]} {example_top/ddr3read_en2[6]} {example_top/ddr3read_en2[7]} {example_top/ddr3read_en2[8]} {example_top/ddr3read_en2[9]} {example_top/ddr3read_en2[10]} {example_top/ddr3read_en2[11]} {example_top/ddr3read_en2[12]} {example_top/ddr3read_en2[13]} {example_top/ddr3read_en2[14]} {example_top/ddr3read_en2[15]} {example_top/ddr3read_en2[16]} {example_top/ddr3read_en2[17]} {example_top/ddr3read_en2[18]} {example_top/ddr3read_en2[19]} {example_top/ddr3read_en2[20]} {example_top/ddr3read_en2[21]} {example_top/ddr3read_en2[22]} {example_top/ddr3read_en2[23]} {example_top/ddr3read_en2[24]}]]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe32 [get_nets [list example_top/Read_Fifo_rden]]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list {MonopulseExThreshould[0]} {MonopulseExThreshould[1]} {MonopulseExThreshould[2]} {MonopulseExThreshould[3]} {MonopulseExThreshould[4]} {MonopulseExThreshould[5]} {MonopulseExThreshould[6]} {MonopulseExThreshould[7]}]]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe4 [get_nets [list SendOver]]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe5 [get_nets [list SendOver1]]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe10 [get_nets [list StartSample]]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list example_top/u_mig_7series_0/u_mig_7series_0_mig/u_ddr3_infrastructure/CLK]]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 29 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {example_top/app_addr[0]} {example_top/app_addr[1]} {example_top/app_addr[2]} {example_top/app_addr[3]} {example_top/app_addr[4]} {example_top/app_addr[5]} {example_top/app_addr[6]} {example_top/app_addr[7]} {example_top/app_addr[8]} {example_top/app_addr[9]} {example_top/app_addr[10]} {example_top/app_addr[11]} {example_top/app_addr[12]} {example_top/app_addr[13]} {example_top/app_addr[14]} {example_top/app_addr[15]} {example_top/app_addr[16]} {example_top/app_addr[17]} {example_top/app_addr[18]} {example_top/app_addr[19]} {example_top/app_addr[20]} {example_top/app_addr[21]} {example_top/app_addr[22]} {example_top/app_addr[23]} {example_top/app_addr[24]} {example_top/app_addr[25]} {example_top/app_addr[26]} {example_top/app_addr[27]} {example_top/app_addr[28]}]]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list example_top/CLK_WIZ_DDR/inst/clk_out2]]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Monopulse_data_vi[7]}]]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list example_top/SendToArm_begin]]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {example_top/Write_Fifo_Out[0]} {example_top/Write_Fifo_Out[1]} {example_top/Write_Fifo_Out[2]} {example_top/Write_Fifo_Out[3]} {example_top/Write_Fifo_Out[4]} {example_top/Write_Fifo_Out[5]} {example_top/Write_Fifo_Out[6]} {example_top/Write_Fifo_Out[7]} {example_top/Write_Fifo_Out[8]} {example_top/Write_Fifo_Out[9]} {example_top/Write_Fifo_Out[10]} {example_top/Write_Fifo_Out[11]} {example_top/Write_Fifo_Out[12]} {example_top/Write_Fifo_Out[13]} {example_top/Write_Fifo_Out[14]} {example_top/Write_Fifo_Out[15]} {example_top/Write_Fifo_Out[16]} {example_top/Write_Fifo_Out[17]} {example_top/Write_Fifo_Out[18]} {example_top/Write_Fifo_Out[19]} {example_top/Write_Fifo_Out[20]} {example_top/Write_Fifo_Out[21]} {example_top/Write_Fifo_Out[22]} {example_top/Write_Fifo_Out[23]} {example_top/Write_Fifo_Out[24]} {example_top/Write_Fifo_Out[25]} {example_top/Write_Fifo_Out[26]} {example_top/Write_Fifo_Out[27]} {example_top/Write_Fifo_Out[28]} {example_top/Write_Fifo_Out[29]} {example_top/Write_Fifo_Out[30]} {example_top/Write_Fifo_Out[31]} {example_top/Write_Fifo_Out[32]} {example_top/Write_Fifo_Out[33]} {example_top/Write_Fifo_Out[34]} {example_top/Write_Fifo_Out[35]} {example_top/Write_Fifo_Out[36]} {example_top/Write_Fifo_Out[37]} {example_top/Write_Fifo_Out[38]} {example_top/Write_Fifo_Out[39]} {example_top/Write_Fifo_Out[40]} {example_top/Write_Fifo_Out[41]} {example_top/Write_Fifo_Out[42]} {example_top/Write_Fifo_Out[43]} {example_top/Write_Fifo_Out[44]} {example_top/Write_Fifo_Out[45]} {example_top/Write_Fifo_Out[46]} {example_top/Write_Fifo_Out[47]} {example_top/Write_Fifo_Out[48]} {example_top/Write_Fifo_Out[49]} {example_top/Write_Fifo_Out[50]} {example_top/Write_Fifo_Out[51]} {example_top/Write_Fifo_Out[52]} {example_top/Write_Fifo_Out[53]} {example_top/Write_Fifo_Out[54]} {example_top/Write_Fifo_Out[55]} {example_top/Write_Fifo_Out[56]} {example_top/Write_Fifo_Out[57]} {example_top/Write_Fifo_Out[58]} {example_top/Write_Fifo_Out[59]} {example_top/Write_Fifo_Out[60]} {example_top/Write_Fifo_Out[61]} {example_top/Write_Fifo_Out[62]} {example_top/Write_Fifo_Out[63]} {example_top/Write_Fifo_Out[64]} {example_top/Write_Fifo_Out[65]} {example_top/Write_Fifo_Out[66]} {example_top/Write_Fifo_Out[67]} {example_top/Write_Fifo_Out[68]} {example_top/Write_Fifo_Out[69]} {example_top/Write_Fifo_Out[70]} {example_top/Write_Fifo_Out[71]} {example_top/Write_Fifo_Out[72]} {example_top/Write_Fifo_Out[73]} {example_top/Write_Fifo_Out[74]} {example_top/Write_Fifo_Out[75]} {example_top/Write_Fifo_Out[76]} {example_top/Write_Fifo_Out[77]} {example_top/Write_Fifo_Out[78]} {example_top/Write_Fifo_Out[79]} {example_top/Write_Fifo_Out[80]} {example_top/Write_Fifo_Out[81]} {example_top/Write_Fifo_Out[82]} {example_top/Write_Fifo_Out[83]} {example_top/Write_Fifo_Out[84]} {example_top/Write_Fifo_Out[85]} {example_top/Write_Fifo_Out[86]} {example_top/Write_Fifo_Out[87]} {example_top/Write_Fifo_Out[88]} {example_top/Write_Fifo_Out[89]} {example_top/Write_Fifo_Out[90]} {example_top/Write_Fifo_Out[91]} {example_top/Write_Fifo_Out[92]} {example_top/Write_Fifo_Out[93]} {example_top/Write_Fifo_Out[94]} {example_top/Write_Fifo_Out[95]} {example_top/Write_Fifo_Out[96]} {example_top/Write_Fifo_Out[97]} {example_top/Write_Fifo_Out[98]} {example_top/Write_Fifo_Out[99]} {example_top/Write_Fifo_Out[100]} {example_top/Write_Fifo_Out[101]} {example_top/Write_Fifo_Out[102]} {example_top/Write_Fifo_Out[103]} {example_top/Write_Fifo_Out[104]} {example_top/Write_Fifo_Out[105]} {example_top/Write_Fifo_Out[106]} {example_top/Write_Fifo_Out[107]} {example_top/Write_Fifo_Out[108]} {example_top/Write_Fifo_Out[109]} {example_top/Write_Fifo_Out[110]} {example_top/Write_Fifo_Out[111]} {example_top/Write_Fifo_Out[112]} {example_top/Write_Fifo_Out[113]} {example_top/Write_Fifo_Out[114]} {example_top/Write_Fifo_Out[115]} {example_top/Write_Fifo_Out[116]} {example_top/Write_Fifo_Out[117]} {example_top/Write_Fifo_Out[118]} {example_top/Write_Fifo_Out[119]} {example_top/Write_Fifo_Out[120]} {example_top/Write_Fifo_Out[121]} {example_top/Write_Fifo_Out[122]} {example_top/Write_Fifo_Out[123]} {example_top/Write_Fifo_Out[124]} {example_top/Write_Fifo_Out[125]} {example_top/Write_Fifo_Out[126]} {example_top/Write_Fifo_Out[127]}]]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {example_top/Write_Fifo_datain[0]} {example_top/Write_Fifo_datain[1]} {example_top/Write_Fifo_datain[2]} {example_top/Write_Fifo_datain[3]} {example_top/Write_Fifo_datain[4]} {example_top/Write_Fifo_datain[5]} {example_top/Write_Fifo_datain[6]} {example_top/Write_Fifo_datain[7]}]]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {example_top/Write_Fifo_rusdw_o[0]} {example_top/Write_Fifo_rusdw_o[1]} {example_top/Write_Fifo_rusdw_o[2]} {example_top/Write_Fifo_rusdw_o[3]} {example_top/Write_Fifo_rusdw_o[4]} {example_top/Write_Fifo_rusdw_o[5]} {example_top/Write_Fifo_rusdw_o[6]} {example_top/Write_Fifo_rusdw_o[7]}]]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {example_top/state[0]} {example_top/state[1]} {example_top/state[2]} {example_top/state[3]}]]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list example_top/Write_Fifo_empty]]
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list example_top/Write_Fifo_full]]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list example_top/Write_Fifo_wr_en]]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[7]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[8]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data2[9]}]]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[7]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/SubtractionMean_data_n[8]}]]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 21 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[7]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[8]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[9]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[10]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[11]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[12]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[13]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[14]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[15]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[16]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[17]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[18]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[19]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Square_data[20]}]]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 41 [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[7]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[8]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[9]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[10]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[11]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[12]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[13]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[14]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[15]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[16]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[17]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[18]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[19]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[20]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[21]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[22]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[23]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[24]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[25]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[26]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[27]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[28]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[29]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[30]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[31]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[32]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[33]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[34]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[35]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[36]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[37]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[38]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[39]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Biquadrate_data[40]}]]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 33 [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[0]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[1]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[2]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[3]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[4]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[5]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[6]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[7]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[8]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[9]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[10]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[11]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[12]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[13]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[14]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[15]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[16]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[17]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[18]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[19]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[20]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[21]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[22]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[23]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[24]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[25]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[26]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[27]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[28]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[29]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[30]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[31]} {example_top/MonopulseEx_Arithmetic1/Arithmetic1/Cube_data[32]}]]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[0]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[1]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[2]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[3]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[4]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[5]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[6]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/Gentle_num[7]}]]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_1/probe7]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe7 [get_nets [list {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[0]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[1]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[2]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[3]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[4]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[5]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[6]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[7]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[8]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[9]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[10]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[11]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[12]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[13]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[14]} {example_top/MonopulseEx_Arithmetic1/Monopulse_extraction_1/send_count[15]}]]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_1/probe8]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe8 [get_nets [list {example_top/Read_Fifo_Out[0]} {example_top/Read_Fifo_Out[1]} {example_top/Read_Fifo_Out[2]} {example_top/Read_Fifo_Out[3]} {example_top/Read_Fifo_Out[4]} {example_top/Read_Fifo_Out[5]} {example_top/Read_Fifo_Out[6]} {example_top/Read_Fifo_Out[7]} {example_top/Read_Fifo_Out[8]} {example_top/Read_Fifo_Out[9]} {example_top/Read_Fifo_Out[10]} {example_top/Read_Fifo_Out[11]} {example_top/Read_Fifo_Out[12]} {example_top/Read_Fifo_Out[13]} {example_top/Read_Fifo_Out[14]} {example_top/Read_Fifo_Out[15]}]]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1/probe9]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe9 [get_nets [list {example_top/feature_num[0]} {example_top/feature_num[1]} {example_top/feature_num[2]} {example_top/feature_num[3]} {example_top/feature_num[4]} {example_top/feature_num[5]} {example_top/feature_num[6]} {example_top/feature_num[7]} {example_top/feature_num[8]} {example_top/feature_num[9]} {example_top/feature_num[10]} {example_top/feature_num[11]} {example_top/feature_num[12]} {example_top/feature_num[13]} {example_top/feature_num[14]} {example_top/feature_num[15]} {example_top/feature_num[16]} {example_top/feature_num[17]} {example_top/feature_num[18]} {example_top/feature_num[19]} {example_top/feature_num[20]} {example_top/feature_num[21]} {example_top/feature_num[22]} {example_top/feature_num[23]} {example_top/feature_num[24]} {example_top/feature_num[25]} {example_top/feature_num[26]} {example_top/feature_num[27]} {example_top/feature_num[28]} {example_top/feature_num[29]} {example_top/feature_num[30]} {example_top/feature_num[31]}]]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe10 [get_nets [list example_top/S_FeatureExtraction_flag_reg1]]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list example_top/SendToArm_Over]]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets FCLK_CLK0_0]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:24 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:25 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:28 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:29 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:30 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:31 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:32 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
