# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.cache/wt [current_project]
set_property parent.project_path E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/1PD/FPGA/My/WaveWidthPhase2/PLToPS1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.runs/AD9481_synth_1/AD9481.dcp
set_property used_in_implementation false [get_files E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.runs/AD9481_synth_1/AD9481.dcp]
read_verilog -library xil_defaultlib {
  E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/imports/imports/Arithmetic1.v
  E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/imports/imports/MonopulseEx_Arithmetic.v
  E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/imports/imports/Monopulse_extraction_1.v
  E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/imports/imports/example_top.v
  E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
add_files E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_emc_0_0/system_axi_emc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/Monopulse_extraction_1/new/Monopulse_extraction_1_ooc.xdc
set_property used_in_implementation false [get_files E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/Monopulse_extraction_1/new/Monopulse_extraction_1_ooc.xdc]

read_xdc -mode out_of_context E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/Arithmetic1/new/Arithmetic1_ooc.xdc
set_property used_in_implementation false [get_files E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/Arithmetic1/new/Arithmetic1_ooc.xdc]

read_xdc E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/constrs_1/imports/imports/example_top.xdc
set_property used_in_implementation false [get_files E:/1PD/FPGA/My/WaveWidthPhase2constrain/PLToPS1.srcs/constrs_1/imports/imports/example_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
